{{- if and (eq (toString .Values.metrics.enabled) "true") .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rediscl.fullname" . }}
  {{- with .Values.metrics.serviceMonitor.prometheusNamespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "rediscl.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.prometheusSelector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    path: {{ .Values.metrics.path }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rediscl.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      serviceMonitor: "true"
{{- end -}}
