apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rediscl.fullname" . }}-probe
  labels:
    {{- include "rediscl.labels" . | nindent 4 }}
data:
  readiness.sh: |
    #!/bin/sh
    set -eu
    CHECK_SERVER="$(redis-cli -p "$1"{{ if .Values.auth.enabled }} -a "$AUTH"{{ end }} ping)"

    if [ "$CHECK_SERVER" != "PONG" ]; then
        echo "Server check failed with: $CHECK_SERVER"
        exit 1
    fi

    exit 0
