{{- $fullname := include "rediscl.fullname" . -}}
{{- $groups := int .Values.groups -}}
{{- $replicas := int .Values.replicas -}}
{{- range $i := until $groups }}
{{- range $j := until $replicas }}
{{- with $ }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-announce-{{ $i }}-{{ $j }}
  labels:
    {{- include "rediscl.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- with .Values.svcAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: redis
  - name: bus
    port: {{ include "rediscl.busPort" . }}
    protocol: TCP
    targetPort: bus
  selector:
    app.kubernetes.io/name: {{ include "rediscl.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-{{ $i }}-{{ $j }}
{{- end }}
{{- end }}
{{- end }}
