apiVersion: v1
kind: Service
metadata:
  name: {{ include "rediscl.fullname" . }}-domain
  labels:
    {{- include "rediscl.labels" . | nindent 4 }}
    serviceMonitor: "true"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- with .Values.svcAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  clusterIP: None
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: redis
  - name: bus
    port: {{ include "rediscl.busPort" . }}
    protocol: TCP
    targetPort: bus
  {{- if eq (toString .Values.metrics.enabled) "true" }}
  - name: metrics
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: metrics
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "rediscl.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
