{{- if and (.Values.auth.enabled) (not .Values.auth.existingMetricsSecret) (.Values.metrics.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-metrics
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.auth.metricsUser | b64enc }}
  password: {{ .Values.auth.metricsPassword | b64enc }}
{{- end -}}
