{{- if and (eq (toString .Values.auth.enabled) "true") (not .Values.auth.existingAdminSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-admin
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.auth.adminUser | b64enc }}
  password: {{ .Values.auth.adminPassword | b64enc }}
{{- end -}}
