{{- if and (.Values.auth.enabled) (not .Values.auth.existingRwanySecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-rwany
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.auth.rwanyUser | b64enc }}
  password: {{ .Values.auth.rwanyPassword | b64enc }}
{{- end -}}
