{{- if and (.Values.auth.enabled) (not .Values.auth.existingKeySecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-keyfile
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  key.txt: {{ .Values.auth.key | b64enc }}
{{- end -}}
