{{- if and (.Values.auth.enabled) (not .Values.auth.existingClusterSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-cluster
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.auth.clusterUser | b64enc }}
  password: {{ .Values.auth.clusterPassword | b64enc }}
{{- end -}}
