apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.fullname" . }}-announce
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  mongodb: {{ include "mongodb.announce" . | quote }}
  mongodbrs: {{ include "mongodb.rsAnnounce" . | quote }}
  mongodb.hidden: {{ include "mongodb.hidden.announce" . | quote }}
