{{- if not .Values.hostNetwork -}}
{{- $fullName := include "redis.fullname" . -}}
{{- $replicas := int .Values.replicas -}}
{{- range $i := until $replicas }}
{{- with $ }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-announce-{{ $i }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- with .Values.svcAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ .Values.sentinel.port }}
    protocol: TCP
    targetPort: sentinel
  selector:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ $fullName }}-{{ $i }}
{{- end }}
{{- end }}
{{- end -}}
