{{- if not .Values.hostNetwork -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-announce
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  sentinel: {{ include "redis.announceAddress" . | quote }}
{{- end -}}
