apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-announce
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis: {{ include "redis.announce" . | quote }}
  redis.insts: {{ include "redis.insts.announce" . | quote }}
