apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-announce
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  masterGroup: {{ include "redis.masterGroup" . | quote }}
  redis: {{ include "redis.announce" . | quote }}
  sentinel: {{ include "redis.sentinel.announce" . | quote }}
