apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rediscluster.fullname" . }}-announce
  labels:
    {{- include "rediscluster.labels" . | nindent 4 }}
data:
  rediscluster: {{ include "rediscluster.announce" . | quote }}
