apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rediscluster.fullname" . }}-probe
  labels:
    {{- include "rediscluster.labels" . | nindent 4 }}
data:
  readiness.sh: |
    #!/bin/sh
    set -eu
    CHECK_SERVER="$(redis-cli -p "$1"{{ if eq (toString .Values.auth.enabled) "true" }} -a "$AUTH"{{ end }} ping)"

    if [ "$CHECK_SERVER" != "PONG" ]; then
        echo "Server check failed with: $CHECK_SERVER"
        exit 1
    fi

    exit 0
