{{- $groups := int .Values.groups -}}
{{- range $i := until $groups }}
{{- with $ }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rediscluster.fullname" . }}-{{ $i }}
  labels:
    {{- include "rediscluster.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rediscluster.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      rediscluster/group: "{{ $i }}"
  serviceName: {{ include "rediscluster.fullname" . }}
  replicas: {{ .Values.replicas }}
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rediscluster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        rediscluster/group: "{{ $i }}"
      annotations:
        checksum/configmap-config: {{ include (print .Template.BasePath "/rediscluster-configmap-config.yaml") . | sha256sum }}
        checksum/configmap-probe: {{ include (print .Template.BasePath "/rediscluster-configmap-probe.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and (eq (toString .Values.metrics.enabled) "true") (.Values.metrics.prometheusDiscovery) }}
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.metrics.path }}
        {{- end }}
    spec:
      {{- with .Values.schedulerName }}
      schedulerName: {{ . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- else }}
      affinity:
        {{- include "rediscluster.podDefaultAffinity" (list . $i) | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      initContainers:
      {{- if eq (toString .Values.initSysctl.enabled) "true" }}
      - name: init-sysctl
        image: {{ .Values.initSysctl.image.repository }}:{{ .Values.initSysctl.image.tag }}
        imagePullPolicy: {{ .Values.initSysctl.image.pullPolicy }}
        command:
          {{- toYaml .Values.initSysctl.command | nindent 10 }}
        securityContext:
          runAsNonRoot: false
          privileged: true
          runAsUser: 0
        {{- if .Values.initSysctl.mountHostSys }}
        volumeMounts:
        - name: host-sys
          mountPath: /host-sys
        {{- end }}
      {{- end }}
      - name: init-config
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - sh
        args:
        - /readonly-config/init.sh
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: REDISCLUSTER_GROUP
          value: "{{ $i }}"
        {{- if eq (toString .Values.auth.enabled) "true" }}
        - name: AUTH
          valueFrom:
            secretKeyRef:
              name: {{ include "rediscluster.authSecret" . }}
              key: password
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /readonly-config
          readOnly: true
        - name: data
          mountPath: /data/store
        {{- with .Values.initConfig.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      containers:
      - name: redis
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - redis-server
        args:
        - /data/store/conf/redis.conf
        {{- if eq (toString .Values.auth.enabled) "true" }}
        env:
        - name: AUTH
          valueFrom:
            secretKeyRef:
              name: {{ include "rediscluster.authSecret" . }}
              key: password
        {{- end }}
        ports:
        - name: redis
          containerPort: {{ .Values.redis.port }}
        - name: bus
          containerPort: {{ include "rediscluster.busPort" . }}
        volumeMounts:
        - name: data
          mountPath: /data/store
        - name: probe
          mountPath: /probe
        readinessProbe:
          exec:
            command: [ "sh", "/probe/readiness.sh", "{{ .Values.redis.port }}" ]
          {{- with .Values.redis.readinessProbe }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        livenessProbe:
          exec:
            command: [ "sh", "/probe/readiness.sh", "{{ .Values.redis.port }}" ]
          {{- with .Values.redis.livenessProbe }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.redis.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if eq (toString .Values.metrics.enabled) "true" }}
      - name: metrics
        image: {{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        args:
        - --web.telemetry-path={{ .Values.metrics.path }}
        - --web.listen-address=:{{ .Values.metrics.port }}
        env:
        - name: REDIS_ADDR
          value: "redis://localhost:{{ .Values.redis.port }}"
        {{- if eq (toString .Values.auth.enabled) "true" }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "rediscluster.authSecret" . }}
              key: password
        {{- end }}
        {{- with .Values.metrics.extraEnvs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
        livenessProbe:
          httpGet:
            path: {{ .Values.metrics.path }}
            port: {{ .Values.metrics.port }}
          {{- with .Values.metrics.livenessProbe }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.metrics.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "rediscluster.fullname" . }}-config
      - name: probe
        configMap:
          name: {{ include "rediscluster.fullname" . }}-probe
      {{- if .Values.initSysctl.mountHostSys }}
      - name: host-sys
        hostPath:
          path: /sys
      {{- end }}
  {{- if eq (toString .Values.persistence.enabled) "false" }}
      - name: data
        emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: data
      {{- with .Values.persistence.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.persistence.accessModes }}
      accessModes:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      {{- if .Values.persistence.storageClass }}
      {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
      {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
