apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongos.fullname" . }}-config
  labels:
    {{- include "mongos.labels" . | nindent 4 }}
data:
  mongos.conf: |
    {{- toYaml .Values.mongos.configmap | nindent 4 }}
