apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongos.fullname" . }}-announce
  labels:
    {{- include "mongos.labels" . | nindent 4 }}
data:
  mongos: {{ include "mongos.announce" . | quote }}
  configsvr: {{ include "mongos.configsvr.announce" . | quote }}
